[firebase]
type = "service_account"
project_id = "haemil-drip-stats"
private_key_id = "b309df04075c4ec3baa1297486cd75d23332d4db"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC4RZ0pnSi96gIE
cdNBXdCsGnISeOcR3Lh+Y83MZy53+Z+xOX1kKFl45AkbJMQwYIpaTeQyr+EnGW5s
DqLBKs46f//g9Y1qvaVGUwEnNlbw0FrHWLnii6Znj1lGrNVA50knScKL4ItHgl31
yzWBJrzrTB7zqRmlFxVAbY5WBLg1iz020rHkO2xmxGQQL44xqPtUaeiMK4WgHNzv
Qx6ylVkrt8RLf8tLVVMCMRKGEhvtBs2ievZC6XOz0uViNIhCZ01d9WA6oWE2CnDA
qdkQrgVGc/sjHmnVlL/Fh5W3cetW2syknNCDtIEN9PrDmcWxAGnT4rRI/f3viFWb
m0232oL1AgMBAAECggEAC6s8MabWLg6RQaL2nStPG/LnGdnbohMvgLDFFxD1TZt6
XBXspZNzilcAZ55gqRftSEd/RaFtw9TVsVSM7xK3nAHqhsjt7gjj3CvvRQJ+fMHo
7w+PN97JiGx4sLkgSPuhyNyKzAz0V5spuYynJE5Qb3hddmcVLLyP4omoK4oheHca
RcfVXfgxB8ioJ7n3g1ZcaylBo6GsAuG4IaAX5nrbpf3nCdS9N/PJiWBUBgODonk/
DdRBmIwE5HaSt2EKv7quz9Joviupd7aKinNrbHe8aPCmL3twiUcu0TaFIacjVz2U
GKRMby42f6NlQ9aMJbhpSUPFjOwRHTNAMR++tB6T8QKBgQDqXKwP3zbgsMWybyC3
Xzxj179EnuV3X7Y9YBAL6OQmLZGlz/AhnEhiHbDeLDWRT+QxXOyzYqsk92JIIBUQ
ChfB1iSsilErjQQA5rhmQj6xv+vmeUgC4VYH/urzn+P5/0yaEA6s149MEbkanVWl
S4neBsG8Ll557DkqaQyYOGaN5QKBgQDJSQYpaoCR0b3oQ5TbUQf7eQGMBoZj1j8X
o8nh8Z9tBGrIkOhmRoI4o16GdtSuzashCOpGYjPYZ2CxiQO1WAbDjlxf3Q0stUjb
RvLzuxzAma+4qWNBNv7p7BsqNgKu1kxnldy8xvQ7qWGgwNII8xmDf7W8M1drIx8h
9nGVX4tP0QKBgQCSHc046BYy6IOZyCdBrKLeLPkXM2oljwr0IRxgEIeONgMEuiwh
CGsooRJQsoeDXagMDr+U6AOEPKiOB1KaeXBubbDX0jThTj4cwbxeJRcpg1r0itEW
2p7kxU5/LkTY7Q85TqGXqZ2x86rQqR9ouzvtrZDEXrSQl3Lcujob/a4S8QKBgQCK
0U/slETjTDGa07D/qFzG8+c7OOzKQeH1XcJHjyoSN2+lrzp3/rykbxcryRxZCgKx
n8JilCuJXZJ0Hjhugqz3hWDzxDHn2YbLo5y+txbXRabIxhlryo/3qBv7+o/TIHxF
HDfGAbhCxUhNY233OiEobZVanFX3z5sTAzHGgMRFYQKBgQDHvm8p8OeGtyxi2rlq
m5yZZZYNooGzyyDRfFbSuiotvQqkFi8zwWVB7r/AT9wDH0hkBx1EirjrZBB1ab2B
KtvLxYvdAgXeul0qMCBa+s0hpYpvHjq4zz287Toe/narRaIxAWiElV0gJSaqAVa0
FvaGwm6iHpttn3/UNmyQT13s7g==
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@haemil-drip-stats.iam.gserviceaccount.com"
client_id = "107575437801203149765"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40haemil-drip-stats.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
